services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saarsinistre-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    depends_on:
      - db
      - redis
    networks:
      - saarsinistre-network

  db:
    image: mysql:8.0
    container_name: saarsinistre-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: saarsinistre
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: saarsinistre_user
      MYSQL_PASSWORD: saarsinistre_password
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - saarsinistre-network

  redis:
    image: redis:7-alpine
    container_name: saarsinistre-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - saarsinistre-network

  nginx:
    image: nginx:alpine
    container_name: saarsinistre-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - saarsinistre-network

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local

networks:
  saarsinistre-network:
    driver: bridge
